name: Push Context Templates

on:
  push:
    branches:
      - main

jobs:
  push-templates:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Prepare Virtual Environment
        run: make prepare

      - name: Install Python dependencies
        run: make install

      - name: Prepare dotenv
        env:
          TEMPLATE_API_URL: ${{ secrets.TEMPLATE_API_URL }}
          TEMPLATE_API_TOKEN: ${{ secrets.TEMPLATE_API_TOKEN }}
        run: make prepare-dotenv

      - name: Push templates
        run: make push-templates
